CREATE TABLE bsclient
(
    NCLIENT_ID INT8         NOT NULL,
    VUSSTATE   VARCHAR(100) NULL,
    VNAME      VARCHAR(255) NOT NULL,
    VSOCIALNUM VARCHAR(255) NULL,
    VBANK      VARCHAR(255) NULL,
    VCCARD     VARCHAR(255) NULL,
    DBEGIN     TIMESTAMP    NOT NULL,
    DEND       TIMESTAMP    NULL,
    VSTATE     VARCHAR(30)  NULL,
    VNOTE      VARCHAR(255) NULL,
    NTCLIENT   INT4         NOT NULL,
    constraint PK_BSCLIENT primary key (NCLIENT_ID)
);
